name: pyomo_ketchup
channels:
  - conda-forge
  - defaults
  - pip
dependencies:
  - openpyxl=3.0.7
  - pandas=1.4.3
  - python=3.8.5
  - scipy=1.8.0
  - cobra=0.26.3
  - ipopt=3.14.1
  - pyomo=6.4.0
  - pip
  - pip:
    - streamlit==1.28.0
